domain: tombomeke.com

production: master

setup:
  - echo "Setup: maak www symlink aan"
  - mkdir -p checkout/master
  - git --work-tree=checkout/master --git-dir=auto.git checkout -f master
  - ln -sfn checkout/master www
